### ISSUE TITLE
Update background image formatting.

### ISSUE THREAD

**Issue by LucasKnezevich** [eknigge/tx_dwgs#43]
Update background image formatting to achieve the following:

- [ ] Cover entire screen/view.
- [ ] Don't repeat.
- [ ] Perhaps make it fixed.

This might be helpful:
https://css-tricks.com/perfect-full-page-background-image/

![Image](https://user-images.githubusercontent.com/46425585/235827061-31f1692e-6f6a-45e7-b865-0b791d14b801.png)

**Comment by ariunzayaE** [comment]
![Image](https://github.com/eknigge/tx_dwgs/assets/81658998/0ba9a606-c1d6-4419-b84b-7038dc53118f)
