### ISSUE TITLE
Update Dropdown item hover background color.

### ISSUE THREAD

**Issue by LucasKnezevich** [eknigge/tx_dwgs#44]
Maybe the background color should be something like white, I think it may look cleaner.  Currently, it is a darker gray.

#### Here's the current state:
![Image](https://user-images.githubusercontent.com/46425585/235828038-961ea967-a226-4017-8afb-ae8475c00035.png)

#### Here's an example of what I was thinking:
![Image](https://user-images.githubusercontent.com/46425585/235827945-91a11b23-91e4-482b-a56b-2aaf0fae1dd9.png)

**Comment by ariunzayaE** [comment]
![Image](https://github.com/eknigge/tx_dwgs/assets/81658998/bd01c657-6e24-4f06-ac3a-06bfd7c13955)

Background color is white now
