### ISSUE TITLE
Update Search Button formatting.

### ISSUE THREAD

**Issue by LucasKnezevich** [eknigge/tx_dwgs#45]
Update Search Button to match current design/color scheme and add a few enhancements.

### Acceptance Criteria:
- [x] Update the button color when pressed to a dark green (currently, it is a dark blue).
- [x] Maybe update button border color (currently, I think it's gray).
- [x] Perhaps make the font a tiny bit larger and perhaps it bold so it 'pops' it bit more.

#### How the button currently looks in its normal state (shows the gray border):
![Image](https://user-images.githubusercontent.com/46425585/235829016-dc9eb41a-19e3-4339-a4d7-7e78c4c31b57.png)

#### How the button currently looks when pressed:
![Image](https://user-images.githubusercontent.com/46425585/235828911-81a34bb9-7059-4f19-bfb2-94c760bceab0.png)

#### Maybe something like this when pressed (this screenshot only shows background color change and font size increase, forgot border color when testing it):
![Image](https://user-images.githubusercontent.com/46425585/235830039-d12db815-e5ee-489b-9add-f75569b8245e.png)

#### Button colors are currently defined on lines 16-18 in `globals.css`:
![Image](https://user-images.githubusercontent.com/46425585/235829208-905e7262-fac9-49f5-8cb6-30a2cac272fd.png)

**Comment by ariunzayaE** [comment]
![Image](https://github.com/eknigge/tx_dwgs/assets/81658998/57fa76df-c993-4b06-8266-d6079bd0666b)



![Image](https://github.com/eknigge/tx_dwgs/assets/81658998/9edff5c3-9de0-4496-926c-e46192a95242)

Before and after
