### ISSUE TITLE
Sort Results Table

### ISSUE THREAD

**Issue by eknigge** [eknigge/tx_dwgs#5]
Update the results table so that it can be sorted by the values in each column. Consider using the bootstrap sortable table.

Testing/Acceptance Criteria:
- user is able to sort each column of the table
- sorting values correctly happens by ascending and descending values
- UI is intuitive and multiple users can operate it without instruction or assistance

**Comment by LucasKnezevich** [comment]
This was implemented when AntD was brought it and was functional when the data source was statically entered into SearchView, but is having issues now that the data is being pulled from the API.  Issue #22 was added to fix that, so closing this one.
